name: create-packages
on:
  push:
    tags:
    - 'v*'
env:
  GH_TOKEN: ${{ github.token }}
  VERSION: ${{ github.ref_name }}
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install make ruby-rubygems -y
      - run: sudo gem install --no-document fpm
      - name: create a deb package
        run: make deb
      - name: create a github release
        run: gh release create $VERSION --generate-notes bin/*.deb
