name: create-packages
on: [push]
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install make ruby-rubygems -y
      - run: sudo gem install --no-document fpm
      - name: create a deb package
        run: make build
      - name: create a github release
        run: gh release create v1.2.3 --generate-notes bin/*.deb
