name: create-packages
on: [push]
jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install make ruby-rubygems -y
      - run: gem install --no-document fpm
      - name: create a deb package
        run: make build
